import MastermindGame from '@games/Mastermind/mastermind';

// import TetrisHead from '@svg/games/tetris-head.svg?react';

const gamePageData = {
  id: 'mastermind',
  title: (
    <>
      <span>Master</span>
      <br />
      <span>mind</span>
    </>
  ),
  link: 'Mastermind',
  icon: null,
  year: '1970',
  complexity: 3,
  controls: (
    <ol>
      <li>
        Use the arrow keys <code>Left</code>, <code>Down</code> &{' '}
        <code>Right</code> to move the falling piece.
      </li>
      <li>
        Press the <code>Spacebar</code> to rotate.
      </li>
    </ol>
  ),
  intro: (
    <>
      <p>
        Moo is a classic logic game that laid the groundwork for many later
        code-breaking games, most notably Mastermind. Developed as a computer
        game in the early 1970s, Moo originated in academic circles and was
        commonly played on early mainframe systems like the PDP series using
        punch cards or basic terminal interfaces. The name "Moo" reflects its
        quirky simplicity and stems from its connection to the earlier
        pencil-and-paper game Bulls and Cows, a game that dates back to at least
        the mid-20th century, possibly earlier, and was popular in Soviet
        Russia.
      </p>
      <p>
        In Moo, the objective is to guess a secret 4-digit number generated by
        the computer, with all digits being unique. After each guess, the
        computer provides feedback in the form of "bulls" and "cows." A bull
        means a digit is correct and in the correct position, while a cow means
        a correct digit is in the wrong position. The player uses this feedback
        to progressively narrow down the possibilities through logical
        deduction. Moo&apos;s charm lay in its elegant minimalism — no flashy
        graphics or sound, just pure mental challenge — making it ideal for
        early computing environments and perfect for teaching logical thinking
        and basic programming.
      </p>
      <p>
        The game&apos;s influence became widespread, especially in educational
        institutions, where it was often used to teach programming concepts and
        problem-solving. Moo&apos;s core mechanics were later refined and
        commercialized in Mastermind (1971), which swapped numbers for colored
        pegs but retained the fundamental gameplay of code-breaking through
        feedback. Despite its obscurity today, Moo holds a significant place in
        the history of computer games as one of the earliest examples of
        turn-based logical deduction implemented digitally.
      </p>
    </>
  ),
  tabs: null,
  game: (props) => <MastermindGame {...props} />,
};

export default gamePageData;
